name: CI/CD Pipeline  

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    #Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2  

    #Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Use the setup-buildx action
      with:
        install: true
        use: true
        driver-opts: |
          image=moby/buildkit:buildx-stable-1
          network=host
      env:
        BUILDX_DEBUG: 1
      

    # Build and Push
    - name: Build and push Docker image
      uses: docker/build-push-action@v2  # Action to build and push
      with:
        context: .  
        push: true  
        tags: user/myapp:latest  

    # Deploy the Docker image 
    - name: Deploy to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push user/myapp:latest